// <auto-generated />
namespace Ampl.Configuration.Tests.EntityFramework.Migrations
{
    using global::System.CodeDom.Compiler;
    using global::System.Data.Entity.Migrations;
    using global::System.Data.Entity.Migrations.Infrastructure;
    using global::System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class M001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M001));
        
        string IMigrationMetadata.Id
        {
            get { return "201602060726580_M001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
