//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampl.Web.Mvc.EditorTemplates.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComplexModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComplexModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ampl.Web.Mvc.EditorTemplates.Web.Resources.ComplexModels", typeof(ComplexModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string BranchInfo_CountryName {
            get {
                return ResourceManager.GetString("BranchInfo_CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel engine.
        /// </summary>
        public static string CarEngine_Diesel {
            get {
                return ResourceManager.GetString("CarEngine_Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pure electric engine (from resource).
        /// </summary>
        public static string CarEngine_Electric {
            get {
                return ResourceManager.GetString("CarEngine_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasoline engine.
        /// </summary>
        public static string CarEngine_Gasoline {
            get {
                return ResourceManager.GetString("CarEngine_Gasoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid electric + diesel engine.
        /// </summary>
        public static string CarEngine_HybridDiesel {
            get {
                return ResourceManager.GetString("CarEngine_HybridDiesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid electric + gasoline engine.
        /// </summary>
        public static string CarEngine_HybridGasoline {
            get {
                return ResourceManager.GetString("CarEngine_HybridGasoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown engine.
        /// </summary>
        public static string CarEngine_Unknown {
            get {
                return ResourceManager.GetString("CarEngine_Unknown", resourceCulture);
            }
        }
    }
}
